spring:
  application:
    name: location-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/uberpoc
    username: ${DB_USER:postgres}
    password: ${DB_PASS:secret}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

app:
  geo:
    search-radius-km: 5.0
    max-results: 20
    drivers-key: "drivers:available"
